_wandb:
    value:
        cli_version: 0.26.1
        e:
            mvi722ic4zd8nf10s6qlr0n46l0zk8du:
                args:
                    - experiment=exp1_mae_meanpool
                codePath: src/train.py
                codePathLocal: src/train.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "13.2"
                disk:
                    /:
                        total: "4227858432"
                        used: "1259302912"
                email: stan.mischler@yahoo.com
                executable: /Data/challenge_sb/.venv/bin/python
                git:
                    commit: 1c8ff180808e4437941bd7498ca920b729c0268a
                    remote: https://github.com/WarrenCod/challenge_sb.git
                gpu: NVIDIA RTX A5000
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 8192
                      memoryTotal: "25757220864"
                      name: NVIDIA RTX A5000
                      uuid: GPU-ba01780f-38f6-fc05-9c41-5fecbc2864a4
                host: jabiru.polytechnique.fr
                memory:
                    total: "66878324736"
                os: Linux-5.14.0-611.49.1.el9_7.x86_64-x86_64-with-glibc2.34
                program: /Data/challenge_sb/src/train.py
                python: CPython 3.12.13
                root: /Data/challenge_sb
                startedAt: "2026-04-25T09:02:06.412121Z"
                writerId: mvi722ic4zd8nf10s6qlr0n46l0zk8du
        m: []
        python_version: 3.12.13
        t:
            "1":
                - 1
                - 41
                - 49
                - 50
                - 63
            "2":
                - 1
                - 41
                - 49
                - 50
                - 63
            "3":
                - 2
                - 13
                - 15
                - 16
                - 61
            "4": 3.12.13
            "5": 0.26.1
            "8":
                - 2
            "12": 0.26.1
            "13": linux-x86_64
dataset:
    value:
        max_samples: null
        num_frames: 4
        seed: 42
        submission_output: /Data/challenge_sb/processed_data/submission.csv
        test_dir: /Data/challenge_sb/processed_data/test
        train_dir: /Data/challenge_sb/processed_data/train
        val_dir: /Data/challenge_sb/processed_data/val
        val_ratio: 0.2
model:
    value:
        classifier:
            name: linear
        name: modular
        num_classes: 33
        spatial:
            checkpoint_path: /Data/challenge_sb/checkpoints/mae_stage1.pt
            drop_path: 0.1
            image_size: 224
            name: vit_mae
            variant: vit_s_16
        temporal:
            name: mean_pool
num_classes:
    value: 33
training:
    value:
        amp: true
        batch_size: 16
        checkpoint_path: /Data/challenge_sb/checkpoints/exp1_mae_meanpool.pt
        device: cuda
        epochs: 50
        grad_clip: 1
        label_smoothing: 0.1
        llrd: 0.75
        lr: 0.001
        num_workers: 8
        resume: true
        warmup_epochs: 5
        weight_decay: 0.05
wandb:
    value:
        enabled: true
        entity: null
        mode: online
        project: csc43m04ep
        run_id: null
        run_name: null
        tags:
            - track1
            - stage2
            - mae
            - meanpool
